-- ============================================================
-- SCHEMA MỞ RỘNG – chạy SAU 00_schema_5bang.sql
-- DANHMUC (12 loại Smart Campus) + BINHLUAN
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE BINHLUAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SUCO DROP CONSTRAINT FK_SC_DANHMUC'; EXCEPTION WHEN OTHERS THEN NULL; END;
  EXECUTE IMMEDIATE 'DROP TABLE DANHMUC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DANHMUC (
    MaDM        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDM       NVARCHAR2(100)  NOT NULL,
    MoTa        NVARCHAR2(500),
    MauSac      VARCHAR2(20)    DEFAULT '#6c757d',
    TrangThai   NUMBER(1)       DEFAULT 1 NOT NULL,
    NgayTao     TIMESTAMP       DEFAULT SYSTIMESTAMP
);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SUCO ADD MaDM NUMBER';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SUCO ADD CONSTRAINT FK_SC_DANHMUC FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2275, -2260) THEN RAISE; END IF;
END;
/

CREATE TABLE BINHLUAN (
    MaBL            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSC            VARCHAR2(10)    NOT NULL,
    MaNguoiViet     NUMBER          NOT NULL,
    NoiDung         NVARCHAR2(2000) NOT NULL,
    ThoiGian        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_BL_SUCO  FOREIGN KEY (MaSC) REFERENCES SUCO(MaSC),
    CONSTRAINT FK_BL_NGUOI FOREIGN KEY (MaNguoiViet) REFERENCES NGUOIDUNG(MaND)
);

DELETE FROM DANHMUC;

-- 12 danh mục liên quan Smart Campus / sự cố CNTT trường học
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Mạng / Wifi', N'Mất kết nối, chậm mạng, wifi thư viện / giảng đường', '#3b82f6');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Phần cứng PC', N'Máy tính hỏng, không boot, màn hình, bàn phím', '#ef4444');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Máy chiếu / AV', N'Máy chiếu, loa, micro phòng học', '#ec4899');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Phần mềm / OS', N'Windows, Office, phần mềm chuyên ngành, license', '#22c55e');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Email / Tài khoản', N'Email trường, SSO, quên mật khẩu, khóa TK', '#8b5cf6');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Máy in / Scan', N'Máy in kẹt giấy, không in, scanner', '#14b8a6');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Server / Data Center', N'Server, lưu trữ, backup, dịch vụ nội bộ', '#1e293b');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'An ninh mạng', N'Tường lửa, VPN, malware, phishing', '#f43f5e');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Điện / Điều hòa / PCCC', N'Mất điện, điều hòa, camera, báo cháy', '#f97316');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Website / Cổng TT', N'Website trường, LMS, cổng đăng ký học phần', '#06b6d4');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Phòng lab / Thực hành', N'Thiết bị lab, phần mềm lab, máy trạm', '#eab308');
INSERT INTO DANHMUC (TenDM, MoTa, MauSac) VALUES (N'Khác', N'Các sự cố không thuộc nhóm trên', '#64748b');

UPDATE SUCO SET MaDM = (SELECT MaDM FROM DANHMUC WHERE TenDM LIKE N'%Máy chiếu%' AND ROWNUM=1)
WHERE TieuDe LIKE N'%Máy chiếu%';
UPDATE SUCO SET MaDM = (SELECT MaDM FROM DANHMUC WHERE TenDM LIKE N'%Mạng%' AND ROWNUM=1)
WHERE TieuDe LIKE N'%Wifi%' OR LOWER(TieuDe) LIKE N'%wifi%' OR TieuDe LIKE N'%mạng%';

COMMIT;
SELECT MaDM, TenDM FROM DANHMUC ORDER BY MaDM;
