-- ============================================================
-- Smart Campus - Schema 5 bang chinh
-- Chay tren Oracle SQL Developer (user: smartcampus)
-- 1) NGUOIDUNG  2) DUAN  3) CONGVIEC  4) SUCO  5) LICHSU
-- ============================================================

-- ========== XOA CU (neu co) ==========
BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
  END LOOP;
END;
/
BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE "' || s.sequence_name || '"';
  END LOOP;
END;
/
BEGIN
  FOR v IN (SELECT view_name FROM user_views) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW "' || v.view_name || '"';
  END LOOP;
END;
/

-- ============================================================
-- 1. NGUOIDUNG  (dang nhap, phan quyen ADMIN / USER)
-- ============================================================
CREATE TABLE NGUOIDUNG (
    MaND        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen       NVARCHAR2(100)  NOT NULL,
    Email       VARCHAR2(100)   NOT NULL,
    MatKhau     VARCHAR2(64)    NOT NULL,   -- MD5 hash
    VaiTro      VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    TrangThai   NUMBER(1)       DEFAULT 1 NOT NULL,  -- 1=Active, 0=Khoa
    NgayTao     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_ND_EMAIL UNIQUE (Email),
    CONSTRAINT CK_ND_VAITRO CHECK (VaiTro IN ('ADMIN', 'USER')),
    CONSTRAINT CK_ND_TRANGTHAI CHECK (TrangThai IN (0, 1))
);

-- ============================================================
-- 2. DUAN  (du an / khu vuc campus: toa nha, he thong IT...)
-- ============================================================
CREATE TABLE DUAN (
    MaDA        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDA       NVARCHAR2(200)  NOT NULL,
    MoTa        NVARCHAR2(1000),
    NgayBatDau  DATE,
    NgayKetThuc DATE,
    TrangThai   VARCHAR2(20)    DEFAULT 'DANG_DIEN_RA' NOT NULL,
    MaQuanLy    NUMBER,          -- Nguoi quan ly du an
    NgayTao     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_DA_TRANGTHAI CHECK (TrangThai IN ('CHUAN_BI', 'DANG_DIEN_RA', 'HOAN_THANH', 'HUY')),
    CONSTRAINT FK_DA_QUANLY FOREIGN KEY (MaQuanLy) REFERENCES NGUOIDUNG(MaND)
);

-- ============================================================
-- 3. CONGVIEC  (cong viec thuoc du an, co the phat sinh su co)
-- ============================================================
CREATE TABLE CONGVIEC (
    MaCV        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDA        NUMBER          NOT NULL,
    TenCV       NVARCHAR2(200)  NOT NULL,
    MoTa        NVARCHAR2(1000),
    MaNguoiLam  NUMBER,          -- Nguoi duoc giao
    MucDo       VARCHAR2(20)    DEFAULT 'TRUNG_BINH' NOT NULL,
    TrangThai   VARCHAR2(20)    DEFAULT 'CHUA_LAM' NOT NULL,
    NgayBatDau  DATE,
    NgayHetHan  DATE,
    NgayTao     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CV_DUAN FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA),
    CONSTRAINT FK_CV_NGUOI FOREIGN KEY (MaNguoiLam) REFERENCES NGUOIDUNG(MaND),
    CONSTRAINT CK_CV_MUCDO CHECK (MucDo IN ('THAP', 'TRUNG_BINH', 'CAO', 'KHAN_CAP')),
    CONSTRAINT CK_CV_TRANGTHAI CHECK (TrangThai IN ('CHUA_LAM', 'DANG_LAM', 'HOAN_THANH', 'HUY'))
);

-- ============================================================
-- 4. SUCO  (su co: co thoi gian + giai phap, lien ket du an/cong viec)
-- ============================================================
CREATE TABLE SUCO (
    MaSC            VARCHAR2(10)    PRIMARY KEY,   -- SC0001...
    TieuDe          NVARCHAR2(200)  NOT NULL,
    MoTa            NVARCHAR2(2000),
    -- Phan loai
    MucDo           VARCHAR2(20)    DEFAULT 'TRUNG_BINH' NOT NULL,
    TrangThai       VARCHAR2(20)    DEFAULT 'MOI' NOT NULL,
    -- Lien ket (tuy chon)
    MaDA            NUMBER,          -- Su co thuoc du an nao
    MaCV            NUMBER,          -- Su co phat sinh tu cong viec nao
    -- Nguoi
    MaNguoiBaoCao   NUMBER          NOT NULL,
    MaNguoiXuLy     NUMBER,
    -- Thoi gian
    NgayTao         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    NgayBatDauXL    TIMESTAMP,       -- Bat dau xu ly
    NgayKetThuc     TIMESTAMP,       -- Hoan tat / dong
    HanXuLy         TIMESTAMP,       -- Deadline (qua han neu SYSDATE > HanXuLy)
    -- Giai phap / kinh nghiem
    NguyenNhan      NVARCHAR2(1000),
    GiaiPhap        NVARCHAR2(2000), -- Cach khac phuc / giai phap
    KetQua          NVARCHAR2(1000),
    -- Rang buoc
    CONSTRAINT FK_SC_DUAN   FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA),
    CONSTRAINT FK_SC_CONGVIEC FOREIGN KEY (MaCV) REFERENCES CONGVIEC(MaCV),
    CONSTRAINT FK_SC_BAOCAO FOREIGN KEY (MaNguoiBaoCao) REFERENCES NGUOIDUNG(MaND),
    CONSTRAINT FK_SC_XULY   FOREIGN KEY (MaNguoiXuLy) REFERENCES NGUOIDUNG(MaND),
    CONSTRAINT CK_SC_MUCDO  CHECK (MucDo IN ('THAP', 'TRUNG_BINH', 'CAO', 'KHAN_CAP')),
    CONSTRAINT CK_SC_TRANGTHAI CHECK (TrangThai IN ('MOI', 'DANG_XU_LY', 'DA_XU_LY', 'DONG'))
);

-- Sequence + Trigger sinh ma SC0001
CREATE SEQUENCE SEQ_SUCO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_SUCO_MA
BEFORE INSERT ON SUCO
FOR EACH ROW
BEGIN
    IF :NEW.MaSC IS NULL THEN
        :NEW.MaSC := 'SC' || LPAD(SEQ_SUCO.NEXTVAL, 4, '0');
    END IF;
END;
/

-- ============================================================
-- 5. LICHSU  (timeline xu ly su co)
-- ============================================================
CREATE TABLE LICHSU (
    MaLS            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSC            VARCHAR2(10)    NOT NULL,
    MaNguoiThucHien NUMBER          NOT NULL,
    TrangThaiCu     VARCHAR2(20),
    TrangThaiMoi    VARCHAR2(20)    NOT NULL,
    GhiChu          NVARCHAR2(1000),
    NguyenNhan      NVARCHAR2(1000),
    GiaiPhap        NVARCHAR2(2000),
    ThoiGian        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_LS_SUCO  FOREIGN KEY (MaSC) REFERENCES SUCO(MaSC),
    CONSTRAINT FK_LS_NGUOI FOREIGN KEY (MaNguoiThucHien) REFERENCES NGUOIDUNG(MaND)
);

-- ============================================================
-- VIEW thong ke (tien dashboard)
-- ============================================================
CREATE OR REPLACE VIEW V_THONGKE_TRANGTHAI AS
SELECT TrangThai, COUNT(*) AS SoLuong FROM SUCO GROUP BY TrangThai;

CREATE OR REPLACE VIEW V_THONGKE_DUAN AS
SELECT d.TenDA, COUNT(s.MaSC) AS SoSuCo
FROM DUAN d
LEFT JOIN SUCO s ON d.MaDA = s.MaDA
GROUP BY d.TenDA;

CREATE OR REPLACE VIEW V_SUCO_QUAHAN AS
SELECT s.*, 
       CASE WHEN s.HanXuLy IS NOT NULL AND s.TrangThai NOT IN ('DONG','DA_XU_LY')
                 AND SYSTIMESTAMP > s.HanXuLy THEN 1 ELSE 0 END AS QuaHan
FROM SUCO s;

-- ============================================================
-- DU LIEU MAU
-- Mat khau 123456 -> MD5 = e10adc3949ba59abbe56e057f20f883e
-- ============================================================
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Admin System', 'admin@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'ADMIN', 1);
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Nguyen Van A', 'user1@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'USER', 1);
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Tran Thi B', 'user2@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'USER', 1);

INSERT INTO DUAN (TenDA, MoTa, NgayBatDau, TrangThai, MaQuanLy) VALUES
(N'Bảo trì cơ sở vật chất 2026', N'Sửa chữa phòng học, thiết bị', DATE '2026-01-01', 'DANG_DIEN_RA', 1);
INSERT INTO DUAN (TenDA, MoTa, NgayBatDau, TrangThai, MaQuanLy) VALUES
(N'Nâng cấp mạng Campus', N'Wifi, switch, server', DATE '2026-03-01', 'DANG_DIEN_RA', 1);
INSERT INTO DUAN (TenDA, MoTa, NgayBatDau, TrangThai, MaQuanLy) VALUES
(N'An ninh & PCCC', N'Camera, báo cháy', DATE '2026-02-15', 'CHUAN_BI', 1);

INSERT INTO CONGVIEC (MaDA, TenCV, MoTa, MaNguoiLam, MucDo, TrangThai, NgayHetHan) VALUES
(1, N'Kiểm tra máy chiếu phòng A101', N'Bảo dưỡng định kỳ', 2, 'TRUNG_BINH', 'DANG_LAM', DATE '2026-10-01');
INSERT INTO CONGVIEC (MaDA, TenCV, MoTa, MaNguoiLam, MucDo, TrangThai, NgayHetHan) VALUES
(2, N'Thay switch tầng 3', N'Nâng băng thông', 2, 'CAO', 'CHUA_LAM', DATE '2026-09-30');
INSERT INTO CONGVIEC (MaDA, TenCV, MoTa, MaNguoiLam, MucDo, TrangThai, NgayHetHan) VALUES
(2, N'Cấu hình Wifi thư viện', N'SSID mới', 3, 'TRUNG_BINH', 'CHUA_LAM', DATE '2026-10-15');

-- Su co mau (MaSC do trigger sinh)
INSERT INTO SUCO (TieuDe, MoTa, MucDo, TrangThai, MaDA, MaCV, MaNguoiBaoCao, MaNguoiXuLy, HanXuLy)
VALUES (N'Máy chiếu A101 không lên hình', N'Đèn báo đỏ, không chiếu được', 'CAO', 'MOI', 1, 1, 2, 2,
        SYSTIMESTAMP + INTERVAL '3' DAY);

INSERT INTO SUCO (TieuDe, MoTa, MucDo, TrangThai, MaDA, MaNguoiBaoCao, HanXuLy)
VALUES (N'Mất Wifi khu thư viện', N'Sinh viên không kết nối được từ sáng', 'KHAN_CAP', 'MOI', 2, 3,
        SYSTIMESTAMP + INTERVAL '1' DAY);

-- Lich su dau tien cho su co
INSERT INTO LICHSU (MaSC, MaNguoiThucHien, TrangThaiCu, TrangThaiMoi, GhiChu)
SELECT MaSC, MaNguoiBaoCao, NULL, 'MOI', N'Tạo sự cố mới' FROM SUCO;

COMMIT;

-- ========== KIEM TRA ==========
SELECT 'NGUOIDUNG' AS BANG, COUNT(*) AS SO_DONG FROM NGUOIDUNG
UNION ALL SELECT 'DUAN', COUNT(*) FROM DUAN
UNION ALL SELECT 'CONGVIEC', COUNT(*) FROM CONGVIEC
UNION ALL SELECT 'SUCO', COUNT(*) FROM SUCO
UNION ALL SELECT 'LICHSU', COUNT(*) FROM LICHSU;

SELECT * FROM SUCO;
