-- ============================================================
-- Smart Campus - Script tao schema (chay tren Oracle SQL Developer)
-- User: smartcampus / smartcampus  (tao user truoc neu chua co)
-- ============================================================

-- ========== BANG NGUOIDUNG ==========
CREATE TABLE NGUOIDUNG (
    MaND        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen       NVARCHAR2(100) NOT NULL,
    Email       VARCHAR2(100) NOT NULL UNIQUE,
    MatKhau     VARCHAR2(64)  NOT NULL,  -- MD5 hash (32 ky tu hex)
    VaiTro      VARCHAR2(20)  NOT NULL CHECK (VaiTro IN ('ADMIN', 'USER')),
    TrangThai   NUMBER(1)     DEFAULT 1 NOT NULL,  -- 1=Active, 0=Khoa
    NgayTao     TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- ========== BANG DANHMUC ==========
CREATE TABLE DANHMUC (
    MaDM        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDM       NVARCHAR2(100) NOT NULL UNIQUE,
    MoTa        NVARCHAR2(255)
);

-- ========== BANG SUCO ==========
CREATE TABLE SUCO (
    MaSC            VARCHAR2(10) PRIMARY KEY,          -- SC0001...
    TieuDe          NVARCHAR2(200) NOT NULL,
    MoTa            NVARCHAR2(2000),
    MaDM            NUMBER NOT NULL REFERENCES DANHMUC(MaDM),
    MucDo           VARCHAR2(20) NOT NULL CHECK (MucDo IN ('THAP', 'TRUNG_BINH', 'CAO', 'KHAN_CAP')),
    TrangThai       VARCHAR2(20) NOT NULL DEFAULT 'MOI'
                        CHECK (TrangThai IN ('MOI', 'DANG_XU_LY', 'DA_XU_LY', 'DONG')),
    MaNguoiBaoCao   NUMBER NOT NULL REFERENCES NGUOIDUNG(MaND),
    MaNguoiXuLy     NUMBER REFERENCES NGUOIDUNG(MaND),
    NgayTao         TIMESTAMP DEFAULT SYSTIMESTAMP,
    NgayCapNhat     TIMESTAMP,
    NguyenNhan      NVARCHAR2(1000),
    CachKhacPhuc    NVARCHAR2(1000)
);

-- Sequence + Trigger sinh ma SC0001, SC0002...
CREATE SEQUENCE SEQ_SUCO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_SUCO_MA
BEFORE INSERT ON SUCO
FOR EACH ROW
BEGIN
    IF :NEW.MaSC IS NULL THEN
        :NEW.MaSC := 'SC' || LPAD(SEQ_SUCO.NEXTVAL, 4, '0');
    END IF;
    :NEW.NgayCapNhat := SYSTIMESTAMP;
END;
/

-- ========== BANG LICHSU_XULY ==========
CREATE TABLE LICHSU_XULY (
    MaLS        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSC        VARCHAR2(10) NOT NULL REFERENCES SUCO(MaSC),
    MaNguoiThucHien NUMBER NOT NULL REFERENCES NGUOIDUNG(MaND),
    TrangThaiCu VARCHAR2(20),
    TrangThaiMoi VARCHAR2(20) NOT NULL,
    GhiChu      NVARCHAR2(1000),
    NguyenNhan  NVARCHAR2(1000),
    CachKhacPhuc NVARCHAR2(1000),
    ThoiGian    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ========== VIEW THONG KE ==========
CREATE OR REPLACE VIEW V_THONGKE_TRANGTHAI AS
SELECT TrangThai, COUNT(*) AS SoLuong
FROM SUCO
GROUP BY TrangThai;

CREATE OR REPLACE VIEW V_THONGKE_DANHMUC AS
SELECT d.TenDM, COUNT(s.MaSC) AS SoLuong
FROM DANHMUC d
LEFT JOIN SUCO s ON d.MaDM = s.MaDM
GROUP BY d.TenDM;

CREATE OR REPLACE VIEW V_THONGKE_THANG AS
SELECT TO_CHAR(NgayTao, 'YYYY-MM') AS Thang, COUNT(*) AS SoLuong
FROM SUCO
GROUP BY TO_CHAR(NgayTao, 'YYYY-MM')
ORDER BY Thang;

-- ========== DU LIEU MAU ==========
-- Mat khau: 123456 -> MD5 = e10adc3949ba59abbe56e057f20f883e
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Admin System', 'admin@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'ADMIN', 1);
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Nguyen Van A', 'user1@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'USER', 1);
INSERT INTO NGUOIDUNG (HoTen, Email, MatKhau, VaiTro, TrangThai) VALUES
(N'Tran Thi B', 'user2@campus.edu', 'e10adc3949ba59abbe56e057f20f883e', 'USER', 1);

INSERT INTO DANHMUC (TenDM, MoTa) VALUES (N'Cơ sở vật chất', N'Sự cố liên quan phòng học, thiết bị');
INSERT INTO DANHMUC (TenDM, MoTa) VALUES (N'Mạng & IT', N'Mạng internet, máy tính, phần mềm');
INSERT INTO DANHMUC (TenDM, MoTa) VALUES (N'An ninh', N'An ninh, an toàn campus');
INSERT INTO DANHMUC (TenDM, MoTa) VALUES (N'Dịch vụ sinh viên', N'Căng tin, ký túc xá, thư viện');
INSERT INTO DANHMUC (TenDM, MoTa) VALUES (N'Khác', N'Các sự cố khác');

COMMIT;
